apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: topolvm.cybozu.com
spec:
  attachRequired: false
  podInfoOnMount: true
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral