kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-global
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-global
subjects:
  - kind: ServiceAccount
    name: topolvm-operator
    namespace: {{ .Release.Namespace }}

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-preparevg
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-preparevg
subjects:
  - kind: ServiceAccount
    name: topolvm-preparevg
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: topolvm-discover
    namespace: {{ .Release.Namespace }}