apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: topolvm-preparevg
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'secret'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/dev/"
      readOnly: false
    - pathPrefix: "/run/udev"
      readOnly: false
    - pathPrefix: "/sys"
      readOnly: false
  hostNetwork: true
  hostPID: true
  hostIPC: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: true
