apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: topolvm-operator
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "watch", "list", "delete", "update", "create" ]
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - secrects
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete
  - apiGroups:
      - apps
      - extensions
    resources:
      - daemonsets
      - statefulsets
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - delete
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - '*'
    verbs:
      - '*'
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: topolvm-preparevg
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - patch
      - create
      - update
      - delete

