apiVersion: v1
kind: Service
metadata:
  name: topolvm-cluster-metric
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
    app.kubernetes.io/compose: metrics
spec:
  selector:
    app.kubernetes.io/name: {{ template "topolvm-operator.fullname" . }}
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: topolvm-node-metric
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
    app.kubernetes.io/compose: metrics
spec:
  selector:
    app.kubernetes.io/compose: node
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080