apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: topolvm.cybozu.com
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
