apiVersion: v1
kind: Service
metadata:
  name: topolvm-controller
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: topolvm-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443

