kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-operator
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: topolvm-operator
subjects:
  - kind: ServiceAccount
    name: topolvm-operator
    namespace: {{ .Release.Namespace }}

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topolvm-preparevg
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: topolvm-preparevg
subjects:
  - kind: ServiceAccount
    name: topolvm-preparevg
    namespace: {{ .Release.Namespace }}
