
apiVersion: v1
kind: ServiceAccount
metadata:
  name: topolvm-operator
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}


---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: topolvm-preparevg
  labels:
    {{- include "topolvm-operator.labels" . | nindent 4 }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: topolvm-discover
  {{- include "topolvm-operator.labels" . | nindent 4 }}

