
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: topolvm-global
rules:
- apiGroups:
  - rawdevice.nativestor.io
  resources:
  - rawdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rawdevice.nativestor.io
  resources:
  - rawdevices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - topolvm.cybozu.com
  resources:
  - topolvmclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - topolvm.cybozu.com
  resources:
  - topolvmclusters/status
  verbs:
  - get
  - patch
  - update
