---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-election
subjects:
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-controller
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-raw-device-provisioner
roleRef:
  kind: Role
  name: leader-election
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-provisioner-role-cfg
subjects:
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-controller
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-raw-device-provisioner
roleRef:
  kind: Role
  name: external-provisioner-cfg
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role-cfg
subjects:
  - kind: ServiceAccount
    name: topolvm-controller
    namespace: topolvm-system
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-raw-device-provisioner
roleRef:
  kind: Role
  name: external-resizer-cfg
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: topolvm-operator
subjects:
  - kind: ServiceAccount
    name: topolvm-operator
    namespace: topolvm-system
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: preparevg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: topolvm-preparevg
subjects:
  - kind: ServiceAccount
    name: topolvm-preparevg
    namespace: topolvm-system
  - kind: ServiceAccount
    name: topolvm-discover
    namespace: topolvm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system-controller
subjects:
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-controller
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-raw-device-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-system-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-provisioner-runner
subjects:
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-controller
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-raw-device-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-external-provisioner-runner
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-resizer-role
subjects:
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-controller
roleRef:
  kind: ClusterRole
  name: topolvm-external-resizer-runner
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-global
subjects:
  - kind: ServiceAccount
    name: topolvm-operator
    namespace: topolvm-system
  - kind: ServiceAccount
    name: topolvm-discover
    namespace: topolvm-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: preparevg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-preparevg
subjects:
  - kind: ServiceAccount
    name: topolvm-preparevg
    namespace: topolvm-system
  - kind: ServiceAccount
    name: topolvm-discover
    namespace: topolvm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node
subjects:
  - kind: ServiceAccount
    name: topolvm-node
    namespace: topolvm-system
  - kind: ServiceAccount
    name: topolvm-raw-device-plugin
    namespace: topolvm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-node