---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: preparevg
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discover
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raw-device-plugin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: raw-device-provisioner