---
apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  selector:
    app.kubernetes.io/name: topolvm-controller
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-metric
  labels:
    app.kubernetes.io/compose: metrics
spec:
  selector:
    name: topolvm-operator
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: node-metric
  labels:
    app.kubernetes.io/compose: metrics
spec:
  selector:
    app.kubernetes.io/compose: node
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
