apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: raw-device-plugin
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: raw-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: raw-device-plugin
    spec:
      containers:
        - name: csi-raw-device-plugin
          command:
            - /raw-device-plugin
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: {{ .RawDeviceImage }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /run/raw-device
              name: node-plugin-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: pod-volumes-dir
            - mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: Bidirectional
              name: csi-plugin-dir
        - name: driver-registrar
          args:
            - "--v={{ .LogLevel }}"
            - "--csi-address=/run/raw-device/csi-rawdevice.sock"
            - "--kubelet-registration-path={{ .KubeletDirPath }}/plugins/rawdevice.nativestor.io/node/csi-rawdevice.sock"
          image: {{ .RegistrarImage }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -rf /registration/rawdevice.nativestor.io /registration/rawdevice.nativestor.io-reg.sock
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /run/raw-device
              name: node-plugin-dir
            - mountPath: /registration
              name: registration-dir
        - name: liveness-prometheus
          args:
            - --csi-address=/run/raw-device/csi-rawdevice.sock
          image: {{ .LivenessImage }}
          imagePullPolicy: IfNotPresent
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /run/raw-device
              name: node-plugin-dir
      hostPID: true
      restartPolicy: Always
      serviceAccountName: topolvm-raw-device-plugin
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: "{{ .KubeletDirPath }}/plugins_registry/"
            type: Directory
          name: registration-dir
        - hostPath:
            path: "{{ .KubeletDirPath }}/plugins/rawdevice.nativestor.io/node"
            type: DirectoryOrCreate
          name: node-plugin-dir
        - hostPath:
            path: "{{ .KubeletDirPath }}/plugins/kubernetes.io/csi"
            type: DirectoryOrCreate
          name: csi-plugin-dir
        - hostPath:
            path: "{{ .KubeletDirPath }}/pods"
            type: DirectoryOrCreate
          name: pod-volumes-dir
