apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nativestor.alauda.io
spec:
  attachRequired: false
  podInfoOnMount: true
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent