apiVersion:  kind.x-k8s.io/v1alpha4
kind: Cluster
# patch the generated kubeadm config with some extra settings
kubeadmConfigPatches:
- |
  apiVersion: "@KUBEADM_APIVERSION@"
  kind: ClusterConfiguration
  metadata:
    name: config
  kubernetesVersion: "v@KUBERNETES_VERSION@"
  networking:
    serviceSubnet: 10.0.0.0/16
  controllerManager:
    extraArgs:
      "v": "5"
- |
  apiVersion: "@KUBEADM_APIVERSION@"
  kind: JoinConfiguration
  metadata:
    name: config
  nodeRegistration:
    kubeletExtraArgs:
      read-only-port: "10255"
# 1 control plane node and 3 workers
nodes:
# the control plane node config
- role: control-plane

- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /run/udev
      hostPath: /run/udev
    - containerPath: /run/lock/lvm
      hostPath: /run/lock/lvm


- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /run/udev
      hostPath: /run/udev
    - containerPath: /run/lock/lvm
      hostPath: /run/lock/lvm

- role: worker
  extraMounts:
    - containerPath: /dev
      hostPath: /dev
    - containerPath: /run/udev
      hostPath: /run/udev
    - containerPath: /run/lock/lvm
      hostPath: /run/lock/lvm
