---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: preparevg
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discover
