name: Main
on:
  pull_request:
    branches:
      - 'main'
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make setup
      - run: make build
      - run: sudo -E env PATH=${PATH}  go test -race -v $(go list ./... | grep -v vendor | grep -v e2e)
      - run: make image
  e2e-k8s:
    name: e2e-k8s
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_kubernetes_target: [current, prev]
    env:
      TEST_KUBERNETES_TARGET: ${{ matrix.test_kubernetes_target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make -C e2e setup
      - run: make -C e2e test
