name: Main
on:
  pull_request:
    branches:
      - 'main'
defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail -x {0}

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make setup
      - run: make build
      - run: sudo -E env PATH=${PATH}  go test -race -v $(go list ./... | grep -v vendor | grep -v e2e)
  e2e-k8s:
    name: e2e-k8s
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_kubernetes_target: [ current, prev ]
    env:
      TEST_KUBERNETES_TARGET: ${{ matrix.test_kubernetes_target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - run: make -C e2e setup
      - run: make -C e2e test
      - name: collect common logs
        if: always()
        run: |
          export LOG_DIR="/home/runner/work/nativestor/tests/integration/_output/tests/"
          export CLUSTER_NAMESPACE="nativestor-system"
          e2e/scripts/collect-logs.sh
      - name: Artifact
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: nativestor-e2e
          path: /home/runner/work/nativestor/tests/integration/_output/tests/
