apiVersion: v1
kind: Service
metadata:
  name: topolvm-node
  labels:
  {{- include "topolvm-operator.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/compose: node
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
